# Introduction

The purpose of this report is to present the findings of the regression analysis for the expansion of the Utah Department of Transportation (UDOT) Incident Management Team (IMT) program and to determine the effect of pertinent variables of crash data on IMT performance and user impacts. In 2019, the Utah Department of Transportation (UDOT) funded a research study to evaluate the effectiveness of an expanded Incident Management Team (IMT) program. The number of IMTs patrolling Utah roadways increased from 13 to 25 between 2018 and 2020. Crash data were collected from the Utah Highway Patrol's (UHP) Computer-Aided Dispatch (CAD) database and from the UDOT TransSuite database for 2018 and 2020. Data were collected to compare IMT performance measures and the user impacts of crashes responded to by IMTs for both years to evaluate the benefits of the expanded IMT program. However, these data were compromised due to the effects of the COVID-19 pandemic.

Because of the unusually low traffic volumes experienced during the COVID-19 pandemic, one of the recommendations from the research was to collect data in a future year without the impacts of COVID-19. The research presented in this report collected data for 2022 using the same methodology as the previous research to compare IMT performance measures and user impacts of crashes in 2022 with those of 2018 after traffic volumes had returned to a similar level as those of pre-pandemic levels. The performance measures collected include IMT Response Time (RT), Roadway Clearance Time (RCT), and IMT Incident Clearance Time (ICT). The study also included the performance measures of UHP RT and UHP ICT but focused primarily on IMT performance measures rather than those of UHP units. The user impacts quantified include the affected volume (AV) of vehicles, excess travel time (ETT) -- or the total delay experienced by all roadway users in a crash, and excess user cost (EUC) -- or the time cost of the delay experienced by all roadway users.

There have been many studies conducted on the benefits of incident management, the potential of large crash data sets to improve ITS capabilities, using machine learning as well as advanced statistical methods to predict incident duration, and estimate generally the reduced delay for incidents which IMTs responded to. However, few studies have been conducted to quantify the user impacts of incidents responded to by IMTs using detailed crash and lane closure data to understand the correlations between specific user impacts and IMT performance measures as well as other crash variables. Relating these variables using detailed incident data allows the benefits of IMTs to be more fully understood as well as guide the allocation of resources to allow highway agencies to decrease the delay and improve the safety experienced by roadway users. The effect of IMT program size is also a variable which has not been specifically addressed.

This manuscript presents a comparison of IMT performance measures and the user impacts of crashes responded to by IMTs for before the program expansion (2018) and after the program expansion (2022). The sections included are a literature review of previous studies, the methods used to obtain and clean crash data for regression analysis, the results of the regression analysis, and the conclusions of the results.
