# Literature Review

Previous studies on Traffic Incident Management (TIM) have explored the effectiveness of the positive effect of IMT program policies on traffic operations and user safety, identifying available data sources used to obtain and quantify IMT performance measures, compiling large data sets for use in ITS to improve crash response, using machine learning and statistical models to predict incident duration occurrence, the development of traffic simulation models based on incident probability to optimize the location of IMTs and quantify delay, and estimate the reduction in delay generally when IMTs respond to a crash.

One study created an open-source platform called DataFITS to collect and fuse traffic-related data (such as volumes, speeds, weather, etc.) from different sources to enhance the coverage and quality of data available to agencies in order to increase the quantity, reliability, and possible applications of Intelligent Transportation Systems (ITS) [@zisner_datafits_2023]. One application for which the heterogeneous data fusion was used for was predicting the speed and volume of traffic in two cities in Germany based on historical data for multiple types of roadways and under different conditions using a polynomial regression model. This yielded models with R^2^ values of up to 0.91 for predicting traffic speed and 0.81 for traffic volume. The other application was an incident classification model that would first evaluate traffic data using an algorithm to classify the binary condition of incident or non-incident based on historical data, which had an accuracy of approximately 90 percent. The platform would then classify the traffic condition as being an incident, congestion, or non-incident, which had an accuracy of approximately 80 percent. This application is an example of the power of having large data sets available to agencies to improve incident response and expand the possibilities of ITS applications such as integrating GIS and traffic data.

A study conducted by researchers at Iowa State University ranked agencies within the state of Iowa based on the effectiveness of its response to incidents based on RCT [@mumtarin_traffic_2023]. A robust Tobit regression model was created for RCT and normalized by controlling for variables that were conditions outside of the agencies' control including crash severity, roadway type, weather conditions, lighting conditions, whether the crash was intersection or interchange related, the kind of intersection or interchange based on available data, the general cause of the crash, and whether it occurred in an urban or rural context. The model indicated that crashes in urban areas were cleared 7.4 minutes faster than those in rural areas. Most adverse weather conditions such as rain, sleet, hail, ice, and light snow had no statistically significant relationship with RCT except for blowing snow and fog/smoke, which increased RCT by 3.3 and 5.2 minutes, respectively. Minor Personal Injury (PI) crashes, major PI crashes, and Fatal and Incapacitating Injury (FII) crashes were shown to have a greater RCT than PDO crashes by 8.7, 28.5, and 108.8 minutes, respectively.

@wali_heterogeneity_2022 analyzed incident duration through three statistical methods including fixed-parameter ordinary least squares (OLS) regression, random effects OLS regression, and quantile regression. The goal of using these statistical methods was to capture and control for the unobserved heterogeneity of factors that influence incident duration. This is a very logical approach due to the inherently random nature of crash incidents. The purpose of including the quantile regression method was to subset and analyze the data in specific ranges including the 25th, 50th, 75th, and 95th percentiles due to the wide range of incident durations that may be experienced; these results also are useful for developing different incident response strategies for a large incident as opposed to medium and small incidents. Overall, the random effects OLS regression model was selected as the best model for predicting incident duration, which might be compared with the results presented in this study as RCT, with an R-squared value of 0.23. Note that all variables in this study were categorical variables.

While many of the studies on incident duration did not specify how this parameter was determined other than through agency-provided data, some studies defined incident duration as ICT while others integrated the speed of traffic into the platform to determine when an incident occurred. The variables of RCT, ICT, and the total time for which the average speed of traffic was significantly below normal (T~7~-T~0~) discussed and analyzed later in this report are comparable to incident duration. While this study also seeks to model IMT performance measures, there has been little work done to model or predict the user impacts of crashes, which are largely dependent on IMT performance measures as well as other pertinent crash variables.

The National Cooperative Highway Research Program (NCHRP) in a report released guidelines on quantifying the benefits of TIM strategies by @shah_development_2022 which states that the reduction of delay (synonymous with ETT) of roadway users is one of the principle metrics used to quantify the effectiveness of an IMT program. Studies therein used traffic models with assumed incident duration times and IMT RT as well as the ratio of lanes closed to the total number of lanes to estimate ETT. Different models found that non-TIM delay is between 1.25 and 2.26 times greater than TIM delay, or the delay when IMTs respond to a crash as opposed to other agencies. However, the limitations of these models are that they rely on simulation data and assumed values of IMT performance measures. Simulations are not able to account for the inherently random, heterogeneous conditions mentioned by @wali_heterogeneity_2022 that occur in crash data as simulations visualize the effects of individual incidents assuming that traffic flows according to rigid assumptions that will not consistently match field conditions.

Other studies previously referenced also show that IMT performance measures vary significantly based on field conditions, for which in-field data sets should be used to verify conditions. While the studies referenced in @shah_development_2022 explored the effects of when IMTs were present as opposed to when they were not present, there have been few studies that have addressed the effect of an expanded IMT program, which findings could considerably benefit many transportation agencies with an existing IMT program.

This analysis is conducted using detailed, in-field incident data for both 2018 and 2022. Statistical models of the user impacts of crashes responded to by IMTs in addition to IMT performance measures provide better understanding of how individual crash variables are correlated with user impacts in addition to performance measures as well as the effect of an expanded IMT program. Results demonstrate that the program expansion accounted for the majority of the reduction of user impacts in 2022 crashes from those of 2018 crashes over IMT performance measures and incident characteristics.
