## Results

```{r setup, file = "R/chapter_start.R", include = FALSE}
# a number of commands need to run at the beginning of each chapter. This
# includes loading libraries that I always use, as well as options for 
# displaying numbers and text.
```

```{r setup2, include = FALSE}
# Other packages ------
# These are packages that get used in this chapter but aren't part of the default set.
```




```{r loadmodels}
tar_load(rt_models)
tar_load(ett_models)
```



```{r tbl-rtmodels}
#| label: tbl-rtmodels
#| tbl-cap: Estimated Models of IMT Response Time
cm <- c(
  "(Intercept)"  = "(Intercept)",
  "typePersonal Injury" = "Personal injury crash (ref. property damage)",
  "typeFatal"    = "Fatal crash (ref. property damage)",
  "lanes_bottle" = "Total lanes on roadway",
  "n_imt"        = "N. IMT units",
  "n_uhp"        = "N. UHP units",
  "year2022"     = "2022 dummy (ref. 2018)"
  )

modelsummary(
  rt_models, 
  stars = TRUE,
  coef_map = cm, 
  notes = list('Dependent variable: $\\log$(Response time).', 
               "Standard errors in parentheses"),
  gof_map = c("nobs", "r.squared", "adj.r.squared"))
```

@tbl-rtmodels shows regression estimates of models predicting the natural log of
the IMT response time. A Base model


```{r tbl-ettmodels}
#| label: tbl-ettmodels
#| tbl-cap: Estimated Models of Excess Travel Time
cm <- c(
  "(Intercept)"  = "(Intercept)",
  "typePersonal Injury" = "Personal injury crash (ref. property damage)",
  "typeFatal"    = "Fatal crash (ref. property damage)",
  "lanes_bottle" = "Total lanes on roadway",
  "n_imt"        = "N. IMT units",
  "n_uhp"        = "N. UHP units",
  "year2022"     = "2022 dummy (ref. 2018)",
  "log(rt_imt)"       = "IMT response time",
  "year2022:log(rt_imt)" = "2022 $\\times$ IMT Response time"
  )

modelsummary(
  ett_models, 
  stars = TRUE,
  coef_map = cm, 
  notes = list('Dependent variable: $\\log$(Excess  travel time).', 
               "Standard errors in parentheses"),
  gof_map = c("nobs", "r.squared", "adj.r.squared"))
```

@tbl-ettmodels shows estimates of regression models predicting the excess travel time.


### Predictions

