# Conclusions

The purpose of this research was to conduct a regression analysis to evaluate the benefits of UDOT's expanded IMT program by evaluating and comparing IMT performance measures for all crashes in 2018 and 2022 that were responded to by IMTs as well as the user impacts quantified for a group of crashes that could be quantified independently. Additionally, regression model results were used to better understand the incident characteristics and crash variables that have the greatest impact on performance measures and user impacts.

The year 2018 variable represents the difference in crash data of the IMT program between years 2018 and 2022 between which the program expanded from 13 units to 25 units. The results of the analysis of this variable show that there was a statistically significant difference between IMT RT in 2018 and 2022 of approximately 2.7 minutes between the two years, showing that the expansion allows IMTs to respond faster to crashes likely due to there being less space between them throughout the coverage area. Ln RCT was found to have a statistically significant difference between 2018 and 2022 where IMTs cleared all lanes of a roadway approximately 16 percent faster in 2018 than in 2022. While the reason for this is not completely understood, it was speculated that contributing factors were post-pandemic IMT protocol to prioritize safety when working with crash victims and the shift in crash distribution to more PI crashes than PDO crashes. There was not found to be any statistically significant difference between IMT ICT in 2018 and 2022.

Each user impact had a statistically significant and practically significant year 2018 variable coefficient that showed that AV decreased by approximately 10 percent between 2018 and 2022 and that both ETT and EUC decreased by approximately 50 percent due to the added number of IMTs in the program. This shows that more IMTs responding to more crashes made a minor reduction to the number of vehicles who experience a decrease in average speed of 20 mph or greater but made a major reduction in the total delay and time cost that all users experience. One of the limitations of the year 2018 variable is that this accounts for all differences between 2018 and 2022 variables not accounted for by other variables, and while it is assumed to primarily account for the difference in IMT program size and the number of units on the road, it may not account for the effect of post-pandemic traffic conditions even though traffic flow rates have largely returned to normal.

The key independent variables that explain each IMT performance measure and their effects are summarized in the following table. The variables with the greatest effect on IMT RT were the number of IMTs that responded to an incident and TWNLC, where each additional IMT that responded was correlated with between 1.5 and 2.0 minutes less RT, and each added lane that was closed for the duration of the incident was correlated with an added 1.9 minutes of RT; this also includes the effect of the number of IMTs within the same model. For RCT, each added minute of IMT RT resulted in a minor increase of approximately e^0.02^, or 2 percent, and each added UHP team and IMT resulted in approximately e^0.11^ and e^0.19^, or 1.12 and 1.21, times higher RCT values, respectively, while also including the effects of IMT RT. The same variables of IMT RT, the number of IMTs, and the number of UHP teams had similar effects on IMT ICT as on RCT but somewhat lower, showing that IMT ICT is not as strongly impacted by these incident characteristics as RCT. However, IMT ICT is affected more by TWNLC than RCT with each added lane closed for the duration of an incident resulting in an 8 percent increase in IMT ICT.

| Independent Variable | IMT RT                              | RCT                                    | IMT ICT                                |
|------------------|------------------|------------------|------------------|
| N. of IMTs           | 1.5-2.0 minutes less per added unit | 21% increase per added unit            | 16% increase per added unit            |
| N. of UHP Teams      | NA                                  | 12% increase per added unit            | 9% increase per added unit             |
| IMT RT               | NA                                  | 2% increase per added minute of IMT RT | 1% increase per added minute of IMT RT |
| TWNLC                | 1.9 minutes more per added lane     | NA                                     | 8% increase per added lane             |

: Impact of Independent Variables on IMT Performance Measures

The year 2018 variable for each user impact model indicates that the expanded IMT program makes a significant difference in the crash effects experienced by roadway users. The increased number of IMTs in the expanded IMT fleet in 2022 accounted for about 11 percent of the decrease in AV from before the program size increase in 2018. For ETT and EUC, the year 2018 coefficient indicates that approximately delay and the monetary cost of time due to it decreased by about 50 percent from 2018 to 2022. These results show that the expanded IMT program and increased number of IMTs responding to crashes minorly decreased the number of vehicles that experience significant delay but that the total delay and monetary cost of time experienced by all roadway users decreases significantly.

The key independent variables that explain user impacts of incidents responded to by IMTs are shown in the table below. The impact of each variable includes the effects of T~7~-T~0~ included within the same model with the exception of T~7~-T~5~ which includes both T~7~-T~0~ and RCT in the same model, which each had a natural log transformation applied to the variable due to the non-linear trends observed in the data. The independent variables which had a natural log transformation taken for them are interpreted relatively in percent changes rather than in units of time due to their effect on user impacts being non-linear. For the purpose of summarizing the impacts of each variable, a 10 percent increase of the independent variable was used to make a standard comparison. See the individual regression model coefficients and the discussion on back-transofrming the variables with natural log transformations applied for predicting incident specific effects.

For the T~7~-T~0~ variable, a 10 percent increase resulted in a 9 percent increase in AV and a larger increase of between 12 to 20 percent in ETT and EUC depending on the specific model and variables included, showing that the time for which speed of traffic is reduced significantly below normal is the primary independent variable influencing delay. A 10 percent increase in T~7~-T~5~ resulted in a 1 percent increase or less in each user impact. RCT was found to not have a statistically significant impact on AV when analyzed in the same model as T~7~-T~0~, and it only increased ETT and EUC by 2 percent for each 10 percent increase.

The number of lanes closed and TWNLC were not found to have a statistically significant effect on AV. However, the impact of 1 additional lane closed at any point during an incident increased ETT and EUC by 46 percent, and the impact of 1 additional lane closed for the duration of an incident increased ETT and EUC by 78 percent. The variable other than T~7~-T~0~ that was found to have the greatest impact on AV was the total number of lanes at the bottleneck of a crash, which caused a 19 percent increase in AV and 21 percent increase in ETT and EUC for each added lane.

| Independent Variable                             | AV                                            | ETT and EUC                                                           |
|------------------------------|---------------------|---------------------|
| T~7~-T~0~                                        | 9% increase per 10% increase in T~7~-T~0~     | 12-20% increase per 10% increase in T~7~-T~0~ (see regression models) |
| T~7~-T~5~                                        | \<1%                                          | 1% increase per 10% increase in T~7~-T~5~                             |
| RCT                                              | NA                                            | 2% increase per 10% increase in RCT                                   |
| N. of Lanes Closed                               | NA                                            | 46% increase per added lane closed at any point during the crash      |
| Time Weighted Number of Lanes Closed (TWNLC)     | NA                                            | 65% increase per added lane closed for the duration of the crash      |
| Total Number of Lanes at the Bottleneck of Crash | 19% increase per added lane at the bottleneck | 21% increase per added lane at the bottleneck                         |

: Impact of Independent Variables on User Impacts

This study is the first of its kind to analyze both IMT performance measures and user impacts for detailed crash data to evaluate the expansion of an existing IMT program. The findings on the expansion of UDOT's IMT program provides a valuable reference point for other transportation agencies potentially considering expanding their own program due to the significant benefits of significantly reduced user impacts associated with additional IMTs responding to more crashes within a given coverage area.

This study also highlights the crash data variables that have the greatest impacts on IMT performance measures and user impacts. While other studies have performed detailed analysis on performance measures given incident characteristics, few studies have incorporated IMT RT to model RCT and ICT. Fewer studies have been conducted on delay and user impacts associated with crashes responded to by IMTs using detailed incident data instead of simulation models, and the findings from this study provide well-fitted, simplistic models reflecting the impacts of incident characteristics and IMT performance measures on user impacts.
