project:
  type: book

# This defines the .qmd files that are in your document
book:
  title: "A Regression Analysis of UDOT's Expanded Incident Management Team Program"
  author:
    - name: Joel Hyer
      orcid: 
      email: 
      affiliations:
        - name: Civil and Construction Engineering Department, Brigham Young University
          address: 430 EB
          city: Provo
          state: UT
          postal-code: 84602
    - name: Grant Schultz
      orcid: 
      email: 
      affiliations:
        - name: Civil and Construction Engineering Department, Brigham Young University
          address: 430 EB
          city: Provo
          state: UT
          postal-code: 84602
    - name: Gregory S. Macfarlane
      orcid: 0000-0003-3999-7584
      email: gregmacfarlane@gmail.com
      affiliations:
        - name: Civil and Construction Engineering Department, Brigham Young University
          address: 430 EB
          city: Provo
          state: UT
          postal-code: 84602
    - name: Dennis Eggett
      orcid: 
      email: 
      affiliations:
        - name: Statistics Department, Brigham Young University
          address: 
          city: Provo
          state: UT
          postal-code: 84602
    # to add additional authors, simply add another -name: tag 
  date: "1/25/2023"
  chapters:
    - index.qmd
    - 01_introduction.qmd
    - 02_litreview.qmd
    - 03_methods.qmd
    - 04_results.qmd
    - 05_conclusion.qmd
    - references.qmd
  abstract: |
    The Utah Department of Transportation's (UDOT's) Incident Management Team (IMT) program was expanded from 13 units in 2018 to 25 units in 2020. This study conducts a regression analysis on the changes in IMT performance measures and the user impacts of crashes responded to by IMTs in the years of 2018 and 2022 to evaluate the benefits of additional IMTs patroling UTah roadways. Crash data were obtained from the Utah Highway Patrol's Computer Aided Dispatch Database and UDOT's TransSuite database to obtain IMT timestamps and lane closures to quantify the IMT performance meaures of response time (RT), roadway clearance time (RCT), and incident clearance time (ICT) as well as the user impacts of the affected volume (AV), excess travel time (ETT), and excess user cost (EUC) for each incident that met established criteria. Results indicate that the IMT program expansion resulted in a statistically significant decrease in IMT RT by appproximately 2.7 mintues between 2018 and 2022 as well as a 10 percent decrease in AV and 50 percent decrease in ETT and EUC due to the program expansion while controlling for other incident charactersitcs. The variables that best explain IMT performance measuers are the number of IMTs responding to a crash, and the time weighted number of lanes closed duirng the crash. User impacts are best explained by the total time for which the average speed of traffic is reduced significantly below normal (T7-T0) as well as the number of lanes closed during the incident. 

bibliography: [references.bib, IMTRegression.bib]

format:
  html:
    theme: cosmo
  elsevier-pdf:
    include-in-header: 
      - packages.tex
    journal:
      name: Transportation Research Part A
      cite-style: authoryear
    keep-tex: true
    top-level-division: section
    toc: false

editor: visual

